# Generated by Django 3.0 on 2020-08-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.EmailField(max_length=254)),
                ('interval', models.PositiveSmallIntegerField()),
                ('message', models.CharField(max_length=255)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
