# Generated by Django 3.0 on 2020-08-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='send_to',
        ),
    ]
